### ISSUE TITLE
Sandpack not working for React Environment

### ISSUE THREAD

**Issue by pranshunagar01** [codesandbox/sandpack#1088] opened 2024-02-23 22:32 UTC
# Bug report

## Packages affected

-   [x] sandpack-client
-   [x] sandpack-react

## Description of the problem
The sandpack has a bug specifically for React environment. It returns this:
 Something went wrong
Cannot read properties of undefined (reading 'join')

### What steps can we take to reproduce the problem?

 
![image](https://github.com/codesandbox/sandpack/assets/59359937/caa7c8f5-4a3e-4078-aa51-8723ccfab138)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by theashishmaurya** [comment] 2024-02-24 15:45
Been facing this issue, I am not sure if any one is working on this or not.

**Comment by fabiobiondi** [comment] 2024-02-24 15:50
Same problem, since yesterday...
We're trying to figure out what's  happened

**Comment by theashishmaurya** [comment] 2024-02-24 15:58
@fabiobiondi  I am also looking into this as of now, will share my finding here, if possible try to make a pr with the solution.

**Comment by fabiobiondi** [comment] 2024-02-24 16:09
@theashishmaurya we have forked  the repo, made several patches (with pnpm patches)  for our needs (so we didn't made PRs) and we're using our CDNs  but if we find the error I'll report here  for sure.

The weird part is that:
1.  the SandPack website has the same problem 
2. we use our CDNs but  we have the same error since yesterday. So we probably forgot to move something on our CDNs 🤔

First of all we need to understand WHERE is the issue but currently we have no idea 😅
We'll work on this in the next hours / days

**Comment by danilowoz** [comment] 2024-02-24 16:22
My bad! I made a silly mistake on the last sandpack version. 
It should be fixed in a couple of minutes in the next release version

**Comment by theashishmaurya** [comment] 2024-02-24 16:24
Hey is it possible you could explain me what went wrong and how you fixed
it? I am still a newbie and learning things.

Ashish

**Closed** 2024-02-24 16:25 UTC
Labels: bug, triage

**Comment by danilowoz** [comment] 2024-02-24 17:25
Sure! Basically, I misplaced the spread operator within the object configuring the Sandpack bundler. This mistake led to an unexpected behavior inside the bundler due to the overwriting of default values.

This caused the error:
```js
this.dispatch({
  type: "compile",
  // other properties I omitted for now
  externalResources: this.options.externalResources || [], 
  sandboxId: this.options.sandboxId,
  ...this.options, // 👈 
})
```

The spread operator (`...this.options`) was placed after all the property assignments and their defaults. As a result, the new spread overwrote all defaults set above because `this.options` also contained `externalResources` property and it's very likely that it was `undefined`. 

Here's two example, one buggy and the another correct:

```js
// 🐞 buggy implementation
const options = {
  externalResources: undefined
}

const foo = {
  externalResources: options.externalResources || [], 
  ...options
}

foo.externalResources // undefined 
```

And here's the correct implementation, which ensure to keep the default values:

```js
// ✅ Correct
const options = {
  externalResources: undefined
}

const foo = {
  ...options,
  externalResources: options.externalResources || [], 
}

foo.externalResources // [] 
```

Hope it helps!
