### ISSUE TITLE
Server timeout issue w/ Workers

### ISSUE THREAD

**Issue by GrossDesignCo** [codesandbox/sandpack#920] opened 2023-04-27 19:18 UTC
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Intermittently the Sandpack instance will throw an error like so:

![CleanShot 2023-04-27 at 12 12 37](https://user-images.githubusercontent.com/5007574/234968232-7d1d0385-4440-4d48-8ede-36401bf5c231.png)

The error appears to be coming from the `sendObjectBeacon` call here:
![CleanShot 2023-04-26 at 14 59 00](https://user-images.githubusercontent.com/5007574/234712537-bf7ceb4f-8071-49be-9a2a-74980649df90.png)

Once one instance fails, all (or nearly all) instances on the same machine also fail with the same error. It seems like it's 

## What were you doing when the problem occurred?

Nothing, this usually happens when leaving a tab alone for a while or walking away from the machine to make coffee :)

### What steps can we take to reproduce the problem?

Appears to happen with a large number of big (we have bundled local imports in the 2-3mb range) Sandpack instances, or with a large number of tabs open that all have Sandpack instances. Happens for all templates.

We're loading them into a Nextjs website. I'd love any tips on getting to a more reliable reproduction if y'all have them :)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |   2.6.0           |
| Sandpack-react version  |  2.6.0            |
| Browser                 |          Chrome 112    |
| Operating System        |       MacOS 13.3.1       |

**Comment by zachmerrill** [comment] 2023-04-29 20:21
Noticing this issue too when I leave a tab too long. The "Try Again" doesn't fix it for me, only a hard refresh of the page.

**Comment by JustJenFelice** [comment] 2023-05-01 14:08
Happens in your own docs as well
![CleanShot 2023-05-01 at 07 06 49](https://user-images.githubusercontent.com/756510/235464041-42f3e213-8d71-4eef-8701-a123dcd881d6.png)

**Comment by danilowoz** [comment] 2023-05-02 09:42
@DeMoorJasper, would you happen to know what's happening on the static template?

**Comment by DeMoorJasper** [comment] 2023-05-02 11:47
Not sure how to reproduce it, but maybe it's a service worker that gets unloaded by the browser and there should be some kind of reload button that reloads the whole app including the service worker?

**Comment by danilowoz** [comment] 2023-05-19 14:41
Pretty sure it's related to https://github.com/codesandbox/sandpack/issues/938

So, I'm going to close it

**Closed by danilowoz** 2023-05-19 14:41 UTC
Labels: bug, triage

**Comment by jerrywu001** [comment] 2023-10-25 03:23
> I notice this issue too when I leave a tab too long. The "Try Again" doesn't fix it for me, only a hard refresh of the page.

The reason why "Try Again" can not take effect is:

rerunning logic in `sandpack-react/src/contexts/utils/useClient.ts` file got an issue

![image](https://github.com/codesandbox/sandpack/assets/12525415/4beb9fae-034a-4c38-908c-ee43a10dd427)

So, **the sandpack client can not restart running it**. you can only see the loading icon in progress.

@danilowoz @DeMoorJasper

**Comment by joshwcomeau** [comment] 2024-01-04 18:29
Hey folks! I've heard from many of my users now who have run into this issue. Not _critical_ since refreshing the page does fix it, but it isn't the best experience.

**Comment by DeMoorJasper** [comment] 2024-01-08 09:26
Tried again with the provided reproduction and still seems like I can't reproduce this, in theory things like the service workers shouldn't time out as they are kept awake automatically by some ping logic we implemented.

**Comment by ionamol** [comment] 2025-07-18 05:09
Since roughly 17 hours ago, every public CodeSandbox I open (React, Vue, vanilla, etc.) - or any sandpack i try to load - immediately throws a error and fails to load the preview.

Reproduction Steps

Open any public sandbox URL, for example:
https://codesandbox.io/s/powder-japan-frontend-0prmq
https://codesandbox.io/s/react-complete-guide-xgxpq
https://codesandbox.io/p/sandbox/thirsty-sound-9lvet?file=/src/index.js

Return when opening the sandbox preview:
{"error":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","stack":"    at async getPreviewInfo (index.js:13973:30)\n    at async request (index.js:14301:31)\n    at async fetch (index.js:14530:16)\n    at async index.js:11060:24\n    at async Object.apply (index.js:11086:16)"}  

Network panel shows requests to https://<sandbox-id>.codesandbox.io/_sandpack_/manifest.json returning HTML (captive portal/error page) and missing CORS headers.

Using Sandpack i always receive this since this morning:

<img width="675" height="740" alt="Image" src="https://github.com/user-attachments/assets/4c78c3c7-5055-443f-a07d-fae5af888522" />


Environment
Occurs on macOS (Safari / Chrome), mobile Safari (cellular data), Incognito/private modes
Happens on home network, no VPN or corporate proxy

**Comment by harugeniee** [comment] 2025-08-28 03:04
I suspect this issue may be related to Cloudflare Workers’ timeout limits. To temporarily address the problem on the client side without requiring a manual page reload (F5), I’ve implemented an Auto-Refresh mechanism that generates a new preview URL automatically. If you have a better idea, please let me know.
